refactor autocomplete for more readability
JoaoDanielRufino/go-input-autocomplete pull request #33
Opened 2020-12-13 13:54 UTC by WheeskyJack

Hi @JoaoDanielRufino 
This PR makes the autocomplete function more readable and easier to understand so that future maintenance is easier.
Regards.

2020-12-13 13:55 UTC, WheeskyJack commented
#7

2020-12-14 14:51 UTC, JoaoDanielRufino requested changes
Really good work, but could you do the same thing on the windowsAutocomplete function? Do you have a Windows environment?

2021-01-22 20:24 UTC, lucasdittrichzup approved these changes

2021-02-04 01:58 UTC, JoaoDanielRufino commented
Hi @WheeskyJack, are you still doing this PR?

2021-02-20 07:49 UTC, WheeskyJack commented
Hi @JoaoDanielRufino ,
very sorry for the delayed response. :(
I am not having windows environment to test. I am doing my dev/testing on centos machine.
So, i may not be able to write the support for windows. Currently I am not doing any active work on this pr.
Regards.

2021-05-07 14:53 UTC, JoaoDanielRufino commented
Closed due inactivity

2021-05-07 14:53 UTC, closed without merging